# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Frontend/*

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  acr: '$(dockerId).azurecr.io/$(imageName)'
  tagged: '$(acr):$(Build.BuildId)'
  latest: '$(acr):latest'

steps:
- script: | 
    docker login -u $(dockerId) -p $pswd $(dockerid).azurecr.io 
    docker build -t $(tagged) -t $(latest) -f ./Frontend/Dockerfile ./Frontend
    docker push $(tagged)
    docker push $(latest)
  env:
    pswd: $(dockerPwd)
